// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_protocal.proto

package com.smart.im.protocal.proto;

public final class MessageProtocalEntity {
  private MessageProtocalEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Protocal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    Header getHeader();
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string body = 2;</code>
     */
    String getBody();
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string body = 2;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code Protocal}
   */
  public  static final class Protocal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Protocal)
      ProtocalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Protocal.newBuilder() to construct.
    private Protocal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Protocal() {
      body_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Protocal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtocalEntity.internal_static_Protocal_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtocalEntity.internal_static_Protocal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protocal.class, Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private Header header_;
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public Header getHeader() {
      return header_ == null ? Header.getDefaultInstance() : header_;
    }
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Header header = 1;</code>
     */
    public HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private volatile Object body_;
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string body = 2;</code>
     */
    public String getBody() {
      Object ref = body_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息体
     * </pre>
     *
     * <code>string body = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protocal)) {
        return super.equals(obj);
      }
      Protocal other = (Protocal) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getBody()
          .equals(other.getBody());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protocal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protocal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protocal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protocal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protocal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protocal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protocal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Protocal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Protocal)
        ProtocalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProtocalEntity.internal_static_Protocal_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProtocalEntity.internal_static_Protocal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protocal.class, Builder.class);
      }

      // Construct using com.smart.im.protocal.proto.MessageProtocalEntity.Protocal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        body_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtocalEntity.internal_static_Protocal_descriptor;
      }

      @Override
      public Protocal getDefaultInstanceForType() {
        return Protocal.getDefaultInstance();
      }

      @Override
      public Protocal build() {
        Protocal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Protocal buildPartial() {
        Protocal result = new Protocal(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protocal) {
          return mergeFrom((Protocal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protocal other) {
        if (other == Protocal.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protocal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protocal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Header header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Header, Header.Builder, HeaderOrBuilder> headerBuilder_;
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      public Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      public Builder setHeader(Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      public Builder setHeader(
          Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      public Builder mergeHeader(Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      public Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      public HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Header, Header.Builder, HeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Header, Header.Builder, HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private Object body_ = "";
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string body = 2;</code>
       */
      public String getBody() {
        Object ref = body_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string body = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string body = 2;</code>
       */
      public Builder setBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string body = 2;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息体
       * </pre>
       *
       * <code>string body = 2;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Protocal)
    }

    // @@protoc_insertion_point(class_scope:Protocal)
    private static final Protocal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protocal();
    }

    public static Protocal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Protocal>
        PARSER = new com.google.protobuf.AbstractParser<Protocal>() {
      @Override
      public Protocal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Protocal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Protocal> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Protocal> getParserForType() {
      return PARSER;
    }

    @Override
    public Protocal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *唯一识别（可以帮助客户端去重）
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    String getId();
    /**
     * <pre>
     *唯一识别（可以帮助客户端去重）
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * 跨端桥接
     * </pre>
     *
     * <code>bool bridge = 2;</code>
     */
    boolean getBridge();

    /**
     * <pre>
     * 协议类型
     * </pre>
     *
     * <code>.ProtocalType protocalType = 3;</code>
     */
    int getProtocalTypeValue();
    /**
     * <pre>
     * 协议类型
     * </pre>
     *
     * <code>.ProtocalType protocalType = 3;</code>
     */
    ProtocalTypeEntity.ProtocalType getProtocalType();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 4;</code>
     */
    int getMessageTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 4;</code>
     */
    MessageTypeEntity.MessageType getMessageType();

    /**
     * <pre>
     *谁发的
     * </pre>
     *
     * <code>string from = 5;</code>
     */
    String getFrom();
    /**
     * <pre>
     *谁发的
     * </pre>
     *
     * <code>string from = 5;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <pre>
     *发给谁
     * </pre>
     *
     * <code>string to = 6;</code>
     */
    String getTo();
    /**
     * <pre>
     *发给谁
     * </pre>
     *
     * <code>string to = 6;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>string groupId = 7;</code>
     */
    String getGroupId();
    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>string groupId = 7;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>bool qoS = 8;</code>
     */
    boolean getQoS();

    /**
     * <pre>
     * </pre>
     *
     * <code>int32 typeu = 9;</code>
     */
    int getTypeu();

    /**
     * <pre>
     * 重试次数
     * </pre>
     *
     * <code>int32 retryCount = 10;</code>
     */
    int getRetryCount();

    /**
     * <pre>
     *服务器接收到消息的时间
     * </pre>
     *
     * <code>sint64 timestamp = 11;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *扩展字段，以key/value形式存放的json
     * </pre>
     *
     * <code>string extend = 12;</code>
     */
    String getExtend();
    /**
     * <pre>
     *扩展字段，以key/value形式存放的json
     * </pre>
     *
     * <code>string extend = 12;</code>
     */
    com.google.protobuf.ByteString
        getExtendBytes();
  }
  /**
   * Protobuf type {@code Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      id_ = "";
      bridge_ = false;
      protocalType_ = 0;
      messageType_ = 0;
      from_ = "";
      to_ = "";
      groupId_ = "";
      qoS_ = false;
      typeu_ = 0;
      retryCount_ = 0;
      timestamp_ = 0L;
      extend_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              bridge_ = input.readBool();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              protocalType_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 64: {

              qoS_ = input.readBool();
              break;
            }
            case 72: {

              typeu_ = input.readInt32();
              break;
            }
            case 80: {

              retryCount_ = input.readInt32();
              break;
            }
            case 88: {

              timestamp_ = input.readSInt64();
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              extend_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtocalEntity.internal_static_Header_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtocalEntity.internal_static_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Header.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <pre>
     *唯一识别（可以帮助客户端去重）
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *唯一识别（可以帮助客户端去重）
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRIDGE_FIELD_NUMBER = 2;
    private boolean bridge_;
    /**
     * <pre>
     * 跨端桥接
     * </pre>
     *
     * <code>bool bridge = 2;</code>
     */
    public boolean getBridge() {
      return bridge_;
    }

    public static final int PROTOCALTYPE_FIELD_NUMBER = 3;
    private int protocalType_;
    /**
     * <pre>
     * 协议类型
     * </pre>
     *
     * <code>.ProtocalType protocalType = 3;</code>
     */
    public int getProtocalTypeValue() {
      return protocalType_;
    }
    /**
     * <pre>
     * 协议类型
     * </pre>
     *
     * <code>.ProtocalType protocalType = 3;</code>
     */
    public ProtocalTypeEntity.ProtocalType getProtocalType() {
      @SuppressWarnings("deprecation")
      ProtocalTypeEntity.ProtocalType result = ProtocalTypeEntity.ProtocalType.valueOf(protocalType_);
      return result == null ? ProtocalTypeEntity.ProtocalType.UNRECOGNIZED : result;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 4;
    private int messageType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 4;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.MessageType messageType = 4;</code>
     */
    public MessageTypeEntity.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      MessageTypeEntity.MessageType result = MessageTypeEntity.MessageType.valueOf(messageType_);
      return result == null ? MessageTypeEntity.MessageType.UNRECOGNIZED : result;
    }

    public static final int FROM_FIELD_NUMBER = 5;
    private volatile Object from_;
    /**
     * <pre>
     *谁发的
     * </pre>
     *
     * <code>string from = 5;</code>
     */
    public String getFrom() {
      Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *谁发的
     * </pre>
     *
     * <code>string from = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 6;
    private volatile Object to_;
    /**
     * <pre>
     *发给谁
     * </pre>
     *
     * <code>string to = 6;</code>
     */
    public String getTo() {
      Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发给谁
     * </pre>
     *
     * <code>string to = 6;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 7;
    private volatile Object groupId_;
    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>string groupId = 7;</code>
     */
    public String getGroupId() {
      Object ref = groupId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>string groupId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QOS_FIELD_NUMBER = 8;
    private boolean qoS_;
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>bool qoS = 8;</code>
     */
    public boolean getQoS() {
      return qoS_;
    }

    public static final int TYPEU_FIELD_NUMBER = 9;
    private int typeu_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int32 typeu = 9;</code>
     */
    public int getTypeu() {
      return typeu_;
    }

    public static final int RETRYCOUNT_FIELD_NUMBER = 10;
    private int retryCount_;
    /**
     * <pre>
     * 重试次数
     * </pre>
     *
     * <code>int32 retryCount = 10;</code>
     */
    public int getRetryCount() {
      return retryCount_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 11;
    private long timestamp_;
    /**
     * <pre>
     *服务器接收到消息的时间
     * </pre>
     *
     * <code>sint64 timestamp = 11;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int EXTEND_FIELD_NUMBER = 12;
    private volatile Object extend_;
    /**
     * <pre>
     *扩展字段，以key/value形式存放的json
     * </pre>
     *
     * <code>string extend = 12;</code>
     */
    public String getExtend() {
      Object ref = extend_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extend_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *扩展字段，以key/value形式存放的json
     * </pre>
     *
     * <code>string extend = 12;</code>
     */
    public com.google.protobuf.ByteString
        getExtendBytes() {
      Object ref = extend_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (bridge_ != false) {
        output.writeBool(2, bridge_);
      }
      if (protocalType_ != ProtocalTypeEntity.ProtocalType.DISCONNET.getNumber()) {
        output.writeEnum(3, protocalType_);
      }
      if (messageType_ != MessageTypeEntity.MessageType.TXT.getNumber()) {
        output.writeEnum(4, messageType_);
      }
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, from_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, to_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, groupId_);
      }
      if (qoS_ != false) {
        output.writeBool(8, qoS_);
      }
      if (typeu_ != 0) {
        output.writeInt32(9, typeu_);
      }
      if (retryCount_ != 0) {
        output.writeInt32(10, retryCount_);
      }
      if (timestamp_ != 0L) {
        output.writeSInt64(11, timestamp_);
      }
      if (!getExtendBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, extend_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (bridge_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, bridge_);
      }
      if (protocalType_ != ProtocalTypeEntity.ProtocalType.DISCONNET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, protocalType_);
      }
      if (messageType_ != MessageTypeEntity.MessageType.TXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, messageType_);
      }
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, from_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, to_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, groupId_);
      }
      if (qoS_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, qoS_);
      }
      if (typeu_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, typeu_);
      }
      if (retryCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, retryCount_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(11, timestamp_);
      }
      if (!getExtendBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, extend_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Header)) {
        return super.equals(obj);
      }
      Header other = (Header) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getBridge()
          == other.getBridge());
      result = result && protocalType_ == other.protocalType_;
      result = result && messageType_ == other.messageType_;
      result = result && getFrom()
          .equals(other.getFrom());
      result = result && getTo()
          .equals(other.getTo());
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && (getQoS()
          == other.getQoS());
      result = result && (getTypeu()
          == other.getTypeu());
      result = result && (getRetryCount()
          == other.getRetryCount());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getExtend()
          .equals(other.getExtend());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + BRIDGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBridge());
      hash = (37 * hash) + PROTOCALTYPE_FIELD_NUMBER;
      hash = (53 * hash) + protocalType_;
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + QOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getQoS());
      hash = (37 * hash) + TYPEU_FIELD_NUMBER;
      hash = (53 * hash) + getTypeu();
      hash = (37 * hash) + RETRYCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getRetryCount();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + EXTEND_FIELD_NUMBER;
      hash = (53 * hash) + getExtend().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Header)
        HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProtocalEntity.internal_static_Header_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProtocalEntity.internal_static_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Header.class, Builder.class);
      }

      // Construct using com.smart.im.protocal.proto.MessageProtocalEntity.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        bridge_ = false;

        protocalType_ = 0;

        messageType_ = 0;

        from_ = "";

        to_ = "";

        groupId_ = "";

        qoS_ = false;

        typeu_ = 0;

        retryCount_ = 0;

        timestamp_ = 0L;

        extend_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtocalEntity.internal_static_Header_descriptor;
      }

      @Override
      public Header getDefaultInstanceForType() {
        return Header.getDefaultInstance();
      }

      @Override
      public Header build() {
        Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Header buildPartial() {
        Header result = new Header(this);
        result.id_ = id_;
        result.bridge_ = bridge_;
        result.protocalType_ = protocalType_;
        result.messageType_ = messageType_;
        result.from_ = from_;
        result.to_ = to_;
        result.groupId_ = groupId_;
        result.qoS_ = qoS_;
        result.typeu_ = typeu_;
        result.retryCount_ = retryCount_;
        result.timestamp_ = timestamp_;
        result.extend_ = extend_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Header) {
          return mergeFrom((Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Header other) {
        if (other == Header.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getBridge() != false) {
          setBridge(other.getBridge());
        }
        if (other.protocalType_ != 0) {
          setProtocalTypeValue(other.getProtocalTypeValue());
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.getQoS() != false) {
          setQoS(other.getQoS());
        }
        if (other.getTypeu() != 0) {
          setTypeu(other.getTypeu());
        }
        if (other.getRetryCount() != 0) {
          setRetryCount(other.getRetryCount());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getExtend().isEmpty()) {
          extend_ = other.extend_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <pre>
       *唯一识别（可以帮助客户端去重）
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *唯一识别（可以帮助客户端去重）
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *唯一识别（可以帮助客户端去重）
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *唯一识别（可以帮助客户端去重）
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *唯一识别（可以帮助客户端去重）
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private boolean bridge_ ;
      /**
       * <pre>
       * 跨端桥接
       * </pre>
       *
       * <code>bool bridge = 2;</code>
       */
      public boolean getBridge() {
        return bridge_;
      }
      /**
       * <pre>
       * 跨端桥接
       * </pre>
       *
       * <code>bool bridge = 2;</code>
       */
      public Builder setBridge(boolean value) {
        
        bridge_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 跨端桥接
       * </pre>
       *
       * <code>bool bridge = 2;</code>
       */
      public Builder clearBridge() {
        
        bridge_ = false;
        onChanged();
        return this;
      }

      private int protocalType_ = 0;
      /**
       * <pre>
       * 协议类型
       * </pre>
       *
       * <code>.ProtocalType protocalType = 3;</code>
       */
      public int getProtocalTypeValue() {
        return protocalType_;
      }
      /**
       * <pre>
       * 协议类型
       * </pre>
       *
       * <code>.ProtocalType protocalType = 3;</code>
       */
      public Builder setProtocalTypeValue(int value) {
        protocalType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议类型
       * </pre>
       *
       * <code>.ProtocalType protocalType = 3;</code>
       */
      public ProtocalTypeEntity.ProtocalType getProtocalType() {
        @SuppressWarnings("deprecation")
        ProtocalTypeEntity.ProtocalType result = ProtocalTypeEntity.ProtocalType.valueOf(protocalType_);
        return result == null ? ProtocalTypeEntity.ProtocalType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 协议类型
       * </pre>
       *
       * <code>.ProtocalType protocalType = 3;</code>
       */
      public Builder setProtocalType(ProtocalTypeEntity.ProtocalType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        protocalType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议类型
       * </pre>
       *
       * <code>.ProtocalType protocalType = 3;</code>
       */
      public Builder clearProtocalType() {
        
        protocalType_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MessageType messageType = 4;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MessageType messageType = 4;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MessageType messageType = 4;</code>
       */
      public MessageTypeEntity.MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        MessageTypeEntity.MessageType result = MessageTypeEntity.MessageType.valueOf(messageType_);
        return result == null ? MessageTypeEntity.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MessageType messageType = 4;</code>
       */
      public Builder setMessageType(MessageTypeEntity.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.MessageType messageType = 4;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private Object from_ = "";
      /**
       * <pre>
       *谁发的
       * </pre>
       *
       * <code>string from = 5;</code>
       */
      public String getFrom() {
        Object ref = from_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *谁发的
       * </pre>
       *
       * <code>string from = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *谁发的
       * </pre>
       *
       * <code>string from = 5;</code>
       */
      public Builder setFrom(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *谁发的
       * </pre>
       *
       * <code>string from = 5;</code>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *谁发的
       * </pre>
       *
       * <code>string from = 5;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private Object to_ = "";
      /**
       * <pre>
       *发给谁
       * </pre>
       *
       * <code>string to = 6;</code>
       */
      public String getTo() {
        Object ref = to_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *发给谁
       * </pre>
       *
       * <code>string to = 6;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发给谁
       * </pre>
       *
       * <code>string to = 6;</code>
       */
      public Builder setTo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发给谁
       * </pre>
       *
       * <code>string to = 6;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发给谁
       * </pre>
       *
       * <code>string to = 6;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private Object groupId_ = "";
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string groupId = 7;</code>
       */
      public String getGroupId() {
        Object ref = groupId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string groupId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string groupId = 7;</code>
       */
      public Builder setGroupId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string groupId = 7;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string groupId = 7;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private boolean qoS_ ;
      /**
       * <pre>
       *心跳
       * </pre>
       *
       * <code>bool qoS = 8;</code>
       */
      public boolean getQoS() {
        return qoS_;
      }
      /**
       * <pre>
       *心跳
       * </pre>
       *
       * <code>bool qoS = 8;</code>
       */
      public Builder setQoS(boolean value) {
        
        qoS_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *心跳
       * </pre>
       *
       * <code>bool qoS = 8;</code>
       */
      public Builder clearQoS() {
        
        qoS_ = false;
        onChanged();
        return this;
      }

      private int typeu_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 typeu = 9;</code>
       */
      public int getTypeu() {
        return typeu_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 typeu = 9;</code>
       */
      public Builder setTypeu(int value) {
        
        typeu_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int32 typeu = 9;</code>
       */
      public Builder clearTypeu() {
        
        typeu_ = 0;
        onChanged();
        return this;
      }

      private int retryCount_ ;
      /**
       * <pre>
       * 重试次数
       * </pre>
       *
       * <code>int32 retryCount = 10;</code>
       */
      public int getRetryCount() {
        return retryCount_;
      }
      /**
       * <pre>
       * 重试次数
       * </pre>
       *
       * <code>int32 retryCount = 10;</code>
       */
      public Builder setRetryCount(int value) {
        
        retryCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重试次数
       * </pre>
       *
       * <code>int32 retryCount = 10;</code>
       */
      public Builder clearRetryCount() {
        
        retryCount_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *服务器接收到消息的时间
       * </pre>
       *
       * <code>sint64 timestamp = 11;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *服务器接收到消息的时间
       * </pre>
       *
       * <code>sint64 timestamp = 11;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器接收到消息的时间
       * </pre>
       *
       * <code>sint64 timestamp = 11;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object extend_ = "";
      /**
       * <pre>
       *扩展字段，以key/value形式存放的json
       * </pre>
       *
       * <code>string extend = 12;</code>
       */
      public String getExtend() {
        Object ref = extend_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extend_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *扩展字段，以key/value形式存放的json
       * </pre>
       *
       * <code>string extend = 12;</code>
       */
      public com.google.protobuf.ByteString
          getExtendBytes() {
        Object ref = extend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *扩展字段，以key/value形式存放的json
       * </pre>
       *
       * <code>string extend = 12;</code>
       */
      public Builder setExtend(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extend_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *扩展字段，以key/value形式存放的json
       * </pre>
       *
       * <code>string extend = 12;</code>
       */
      public Builder clearExtend() {
        
        extend_ = getDefaultInstance().getExtend();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *扩展字段，以key/value形式存放的json
       * </pre>
       *
       * <code>string extend = 12;</code>
       */
      public Builder setExtendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extend_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Header)
    }

    // @@protoc_insertion_point(class_scope:Header)
    private static final Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Header();
    }

    public static Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @Override
    public Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocal_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026message_protocal.proto\032\023protocal_type." +
      "proto\032\022message_type.proto\"1\n\010Protocal\022\027\n" +
      "\006header\030\001 \001(\0132\007.Header\022\014\n\004body\030\002 \001(\t\"\352\001\n" +
      "\006Header\022\n\n\002id\030\001 \001(\t\022\016\n\006bridge\030\002 \001(\010\022#\n\014p" +
      "rotocalType\030\003 \001(\0162\r.ProtocalType\022!\n\013mess" +
      "ageType\030\004 \001(\0162\014.MessageType\022\014\n\004from\030\005 \001(" +
      "\t\022\n\n\002to\030\006 \001(\t\022\017\n\007groupId\030\007 \001(\t\022\013\n\003qoS\030\010 " +
      "\001(\010\022\r\n\005typeu\030\t \001(\005\022\022\n\nretryCount\030\n \001(\005\022\021" +
      "\n\ttimestamp\030\013 \001(\022\022\016\n\006extend\030\014 \001(\tB4\n\033com" +
      ".smart.im.protocal.protoB\025MessageProtoca" +
      "lEntityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProtocalTypeEntity.getDescriptor(),
          MessageTypeEntity.getDescriptor(),
        }, assigner);
    internal_static_Protocal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protocal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocal_descriptor,
        new String[] { "Header", "Body", });
    internal_static_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Header_descriptor,
        new String[] { "Id", "Bridge", "ProtocalType", "MessageType", "From", "To", "GroupId", "QoS", "Typeu", "RetryCount", "Timestamp", "Extend", });
    ProtocalTypeEntity.getDescriptor();
    MessageTypeEntity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
