// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocal_type.proto

package com.smart.im.protocal.proto;

public final class ProtocalTypeEntity {
  private ProtocalTypeEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ProtocalType}
   */
  public enum ProtocalType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *断开连接
     * </pre>
     *
     * <code>DISCONNET = 0;</code>
     */
    DISCONNET(0),
    /**
     * <pre>
     *连接
     * </pre>
     *
     * <code>CONNECT = 1;</code>
     */
    CONNECT(1),
    /**
     * <pre>
     *连接回应
     * </pre>
     *
     * <code>CONNACK = 2;</code>
     */
    CONNACK(2),
    /**
     * <pre>
     *发送
     * </pre>
     *
     * <code>PUBLISH = 3;</code>
     */
    PUBLISH(3),
    /**
     * <pre>
     *发送回应
     * </pre>
     *
     * <code>PUBACK = 4;</code>
     */
    PUBACK(4),
    /**
     * <pre>
     *接收
     * </pre>
     *
     * <code>RECEIVE = 5;</code>
     */
    RECEIVE(5),
    /**
     * <pre>
     *接收回应
     * </pre>
     *
     * <code>RECEACK = 6;</code>
     */
    RECEACK(6),
    /**
     * <pre>
     *心跳请求
     * </pre>
     *
     * <code>PINGREQ = 7;</code>
     */
    PINGREQ(7),
    /**
     * <pre>
     *心跳回应
     * </pre>
     *
     * <code>PINGRESP = 8;</code>
     */
    PINGRESP(8),
    /**
     * <pre>
     *错误返回
     * </pre>
     *
     * <code>ERRORESP = 9;</code>
     */
    ERRORESP(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *断开连接
     * </pre>
     *
     * <code>DISCONNET = 0;</code>
     */
    public static final int DISCONNET_VALUE = 0;
    /**
     * <pre>
     *连接
     * </pre>
     *
     * <code>CONNECT = 1;</code>
     */
    public static final int CONNECT_VALUE = 1;
    /**
     * <pre>
     *连接回应
     * </pre>
     *
     * <code>CONNACK = 2;</code>
     */
    public static final int CONNACK_VALUE = 2;
    /**
     * <pre>
     *发送
     * </pre>
     *
     * <code>PUBLISH = 3;</code>
     */
    public static final int PUBLISH_VALUE = 3;
    /**
     * <pre>
     *发送回应
     * </pre>
     *
     * <code>PUBACK = 4;</code>
     */
    public static final int PUBACK_VALUE = 4;
    /**
     * <pre>
     *接收
     * </pre>
     *
     * <code>RECEIVE = 5;</code>
     */
    public static final int RECEIVE_VALUE = 5;
    /**
     * <pre>
     *接收回应
     * </pre>
     *
     * <code>RECEACK = 6;</code>
     */
    public static final int RECEACK_VALUE = 6;
    /**
     * <pre>
     *心跳请求
     * </pre>
     *
     * <code>PINGREQ = 7;</code>
     */
    public static final int PINGREQ_VALUE = 7;
    /**
     * <pre>
     *心跳回应
     * </pre>
     *
     * <code>PINGRESP = 8;</code>
     */
    public static final int PINGRESP_VALUE = 8;
    /**
     * <pre>
     *错误返回
     * </pre>
     *
     * <code>ERRORESP = 9;</code>
     */
    public static final int ERRORESP_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ProtocalType valueOf(int value) {
      return forNumber(value);
    }

    public static ProtocalType forNumber(int value) {
      switch (value) {
        case 0: return DISCONNET;
        case 1: return CONNECT;
        case 2: return CONNACK;
        case 3: return PUBLISH;
        case 4: return PUBACK;
        case 5: return RECEIVE;
        case 6: return RECEACK;
        case 7: return PINGREQ;
        case 8: return PINGRESP;
        case 9: return ERRORESP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocalType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtocalType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocalType>() {
            public ProtocalType findValueByNumber(int number) {
              return ProtocalType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtocalTypeEntity.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtocalType[] VALUES = values();

    public static ProtocalType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtocalType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtocalType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023protocal_type.proto*\223\001\n\014ProtocalType\022\r" +
      "\n\tDISCONNET\020\000\022\013\n\007CONNECT\020\001\022\013\n\007CONNACK\020\002\022" +
      "\013\n\007PUBLISH\020\003\022\n\n\006PUBACK\020\004\022\013\n\007RECEIVE\020\005\022\013\n" +
      "\007RECEACK\020\006\022\013\n\007PINGREQ\020\007\022\014\n\010PINGRESP\020\010\022\014\n" +
      "\010ERRORESP\020\tB1\n\033com.smart.im.protocal.pro" +
      "toB\022ProtocalTypeEntityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
